### ISSUE TITLE
[docker]Which branch is for the stable version? And I failed all branch to build docker img.

### ISSUE THREAD

**Issue by LiuWhale** [MenxLi/Lires#13]

**Comment by MenxLi** [comment]
Thank you for your interest in this app, I initially did not expect it to receive much attention, so the development has been somewhat casual...

Please refer to the most up-to-date doc for docker usage: [run with docker](https://github.com/MenxLi/Lires/blob/dev/docs/src/deployment/gettingStarted.md#run-with-docker)  

I'm not using docker much, so there may have issues with it...  
I checked your screenshots, it seems the error come from 2 sources: 
1. I'm migrating to vitepress for documentation, but the docker image is not updated yet, I've fixed it in this commit: d3c4f0f9750fa83b16ae736a0e757c9a6ee342e7 
2. `CERT_HAS_EXPIRED` seems like a network issue, I'm not sure if it's related to the `cnpm` I'm using, but the latest one should be using `npm` instead.

You can try to pull the latest changes on the `dev` branch, and see if it works.  

As of your question, the `main` branch is the stable version, and the `dev` is the one I'm working on. 
The other branches are too old, just for reference, you can ignore them.

**Comment by LiuWhale** [comment]
> Thank you for your interest in this app, I initially did not expect it to receive much attention, so the development has been somewhat casual...
> 
> Please refer to the most up-to-date doc for docker usage: [run with docker](https://github.com/MenxLi/Lires/blob/dev/docs/src/deployment/gettingStarted.md#run-with-docker)
> 
> I'm not using docker much, so there may have issues with it... I checked your screenshots, it seems the error come from 2 sources:
> 
> 1. I'm migrating to vitepress for documentation, but the docker image is not updated yet, I've fixed it in this commit: [d3c4f0f](https://github.com/MenxLi/Lires/commit/d3c4f0f9750fa83b16ae736a0e757c9a6ee342e7)
> 2. `CERT_HAS_EXPIRED` seems like a network issue, I'm not sure if it's related to the `cnpm` I'm using, but the latest one should be using `npm` instead.
> 
> You can try to pull the latest changes on the `dev` branch, and see if it works.
> 
> As of your question, the `main` branch is the stable version, and the `dev` is the one I'm working on. The other branches are too old, just for reference, you can ignore them.

<img width="731" alt="image" src="https://github.com/MenxLi/Lires/assets/20088521/aef90b37-8ef0-4427-82d6-4c2e0ba6416c">
Thanks, bro. it's succeed on commit https://github.com/MenxLi/Lires/commit/d3c4f0f9750fa83b16ae736a0e757c9a6ee342e7
