### ISSUE TITLE
[docker][AI] cannot pull service up while setting env variable

### ISSUE THREAD

**Issue by LiuWhale** [MenxLi/Lires#14]
Reality:
<img width="132" alt="image" src="https://github.com/MenxLi/Lires/assets/20088521/e85f56ea-06f0-4825-a563-5aa2654011ac">
Expected：
<img width="177" alt="image" src="https://github.com/MenxLi/Lires/assets/20088521/db06f518-6342-43d4-86dc-47a93f187168">
And also the website cannot be opened.
What I exec:
docker run -d -p 9096:8080 -v /lires_data/:/root/.Lires --restart=always --gpus all -e OPENAI_API_BASE=xxxxxx -e OPENAI_API_KEY=xxxxx --name lrs   lires:latest

**Comment by MenxLi** [comment]
Hi, I failed to re-produce this in my machine, the same command works. 
Can you start the docker with a tty to check if there are any error messages? i.e.
```
docker run -it -p ...
```

By the way, there are some issues with the command you provided: 

1. The docker image is running the `lrs-cluster` script under the hood, 
which is a wrapper script that sets up the arguments and environment variables 
in a configuration file (mounted at `$LRS_HOME/container-cluster-config.yaml`).
So, you should not specify the environment variables in the command (you can do this as long as the variables is not override by the configuration file), but rather change the configuration file.
2. The log not showing the `server` entry does not mean that the server is not running. 
The server log will be produced once the first request is made to the server. 
To check if the server is running, you can use `lrs-status --process` to see if the server process is running.
if something like: 
`
/usr/local/bin/python /usr/local/bin/lires server --port 8080
`
is shown, then the server is running.
3. The docker is using the `python` image (not `cuda`), so the `--gpus` may not work.

Anyway, the same command works for me, so please try the above suggestions and let me know if it works.

**Comment by MenxLi** [comment]
oops... the current configuration file is actually using toml, please ignore the `.yaml` extension...

**Comment by LiuWhale** [comment]
`docker run -d -p 9096:8080 --restart=always --gpus all -e OPENAI_API_BASE=xxxxxx -e OPENAI_API_KEY=xxxxx --name lrs lires:latest`
This command is ok, and another Question. lol
Can I use the ai summary without config like openai_api?

**Comment by MenxLi** [comment]
Since you successfully started the container without specifying mount point, 
I suspect that the problem is with the file inside the mounted directory. 
(
    Maybe there is a lock file or something that prevents the application from starting, 
    Or maybe the configuration file is malformed.
)
But I failed to reproduce the problem, and cannot be sure about the cause.
Instead of `-d` You can try to run it with `-it` to see the stdout of the container.
```
docker run -it -p 9096:8080 -v /lires_data/:/root/.Lires ...
```
In this way, you can see the stdout of the container and see if there is any error message.

As of the second question, 
currently, NO. 
You can only use the AI summary feature if OPENAI_API_KEY is available.

If you want to use self-hosted LLM, you can use tools like [vllm](https://github.com/vllm-project/vllm) 
to host your own openai compatible API server.
and specify the API endpoint and model name with the `lires ai` starting command arguments.

**By the way, in the future I am planning to make the LLM to frontend and let the end-user use it with their own API key.**

In addition, the AI summary is not very well written at this time-point, 
It's just a method for fun and should not be better than the original abstract :)

**Comment by LiuWhale** [comment]
> Since you successfully started the container without specifying mount point, I suspect that the problem is with the file inside the mounted directory. ( Maybe there is a lock file or something that prevents the application from starting, Or maybe the configuration file is malformed. ) But I failed to reproduce the problem, and cannot be sure about the cause. Instead of `-d` You can try to run it with `-it` to see the stdout of the container.
> 
> ```
> docker run -it -p 9096:8080 -v /lires_data/:/root/.Lires ...
> ```
> 
> In this way, you can see the stdout of the container and see if there is any error message.
> 
> As of the second question, currently, NO. You can only use the AI summary feature if OPENAI_API_KEY is available.
> 
> If you want to use self-hosted LLM, you can use tools like [vllm](https://github.com/vllm-project/vllm) to host your own openai compatible API server. and specify the API endpoint and model name with the `lires ai` starting command arguments.
> 
> **By the way, in the future I am planning to make the LLM to frontend and let the end-user use it with their own API key.**
> 
> In addition, the AI summary is not very well written at this time-point, It's just a method for fun and should not be better than the original abstract :)

<img width="1297" alt="image" src="https://github.com/MenxLi/Lires/assets/20088521/35ba4752-9f2e-430b-8895-bf11b73b957b">


bro, check this conflict.

**Comment by LiuWhale** [comment]
And we have another problem.
<img width="878" alt="image" src="https://github.com/MenxLi/Lires/assets/20088521/434d8ba5-34da-4975-a96a-6c8ea2deb68b">
`docker run -d -p 9096:8080 -v /lires_data/:/root/.Lires --restart=always  --name lrs lires:latest`

**Comment by MenxLi** [comment]
> > Since you successfully started the container without specifying mount point, I suspect that the problem is with the file inside the mounted directory. ( Maybe there is a lock file or something that prevents the application from starting, Or maybe the configuration file is malformed. ) But I failed to reproduce the problem, and cannot be sure about the cause. Instead of `-d` You can try to run it with `-it` to see the stdout of the container.
> > ```
> > docker run -it -p 9096:8080 -v /lires_data/:/root/.Lires ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In this way, you can see the stdout of the container and see if there is any error message.
> > As of the second question, currently, NO. You can only use the AI summary feature if OPENAI_API_KEY is available.
> > If you want to use self-hosted LLM, you can use tools like [vllm](https://github.com/vllm-project/vllm) to host your own openai compatible API server. and specify the API endpoint and model name with the `lires ai` starting command arguments.
> > **By the way, in the future I am planning to make the LLM to frontend and let the end-user use it with their own API key.**
> > In addition, the AI summary is not very well written at this time-point, It's just a method for fun and should not be better than the original abstract :)
> 
> <img alt="image" width="1297" src="https://private-user-images.githubusercontent.com/20088521/321530299-35ba4752-9f2e-430b-8895-bf11b73b957b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjAxMDcsIm5iZiI6MTcxMjgxOTgwNywicGF0aCI6Ii8yMDA4ODUyMS8zMjE1MzAyOTktMzViYTQ3NTItOWYyZS00MzBiLTg4OTUtYmYxMWI3M2I5NTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA3MTY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YzZmNDk0ZTIxOWExZDZiMWQ3YjMzYzc1ZTRjYWYzMWRmNGFmNzg0ZDQyNjM5MTViYTY3ZGNmOTMyYzZiMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kbHcoPxnf8GTRxR19phPXGKQFOz9WrMzyqyVHsqQPSo">
> 
> bro, check this conflict.

Hi, I did not see errors on this screenshot, the conflict warning should be fine, I see this in my side as well, it will not a big issue and I may fix this in the future. 

However I'm not sure if you successfully finished downloading the pdf.js, because I don't see the finish hint in the snapshot. 
Perhaps you have some network issue that prevent you from downloading, and this downloading process blocks the server  starting,   
you may try to run `lrs-utils update_pdfjs` manually and ensure it indeed successed, then start the server again.

**Comment by MenxLi** [comment]
> And we have another problem. <img alt="image" width="854" src="https://private-user-images.githubusercontent.com/20088521/321532193-cff9f28a-8b26-44d3-ac05-744e758bf7a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjAxMDcsIm5iZiI6MTcxMjgxOTgwNywicGF0aCI6Ii8yMDA4ODUyMS8zMjE1MzIxOTMtY2ZmOWYyOGEtOGIyNi00NGQzLWFjMDUtNzQ0ZTc1OGJmN2EwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA3MTY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNGUxOWI4NWRjODE5ZjBlZDk1MzU4MTE1MjNlYzczNzczMWFlNjUxNzc3NjVkMjYwYmYxZTQzNjk4YjBmNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.thQMCX1jIjWFUOT_vDsEAuR-VpQaQIOByfsVqclALAc"> `docker run -d -p 9096:8080 -v /lires_data/:/root/.Lires --restart=always --name lrs lires:latest`

Thank you for finding this bug, 
this is due to the illegal charactor in collected bibtex, 
it rarely happen, and I have fixed it in 1281c41feb3b5f39c64877e562d4916788f11fb3

However, this will not lead to blocking of the server starting, please still try the above solutions and see if it works

**Comment by thormaxx** [comment]
@LiuWhale 你好，我直接在Ubuntu上安装，到lires register那一步进行不下去了，请问你的docker方案可以正常运行吗？我是个新手，不想折腾了

**Comment by MenxLi** [comment]
> @LiuWhale 你好，我直接在Ubuntu上安装，到lires register那一步进行不下去了，请问你的docker方案可以正常运行吗？我是个新手，不想折腾了

运行`registry`为啥进行不下去呢？可以另开一个issue描述一下问题！

**Comment by MenxLi** [comment]
close due to inactive
