### ISSUE TITLE
纯新手，碰到的问题，请指教

### ISSUE THREAD

**Issue by thormaxx** [MenxLi/Lires#15]
纯新手，开始以为这几个命令是都要一次性运行的：
```
registry            Start lires registry server
    server              Start lires main server
    ai                  Start lires ai server
    log                 Start lires log server
    feed                Start lires feed server
```
后来发现一次似乎只要运行一个就行，不知道这样理解对不对。
运行第一行`lires registry`，基本上是一路缺啥pip啥，最后提示`Starting service at: http://127.0.0.1:8700`。我是在局域网中的一个Ubuntu服务器上远程安装的，所以使用了`http://局域网服务器ip:8700` 尝试打开网页，没成功，是要用nginx做反向代理吗？

一路pip后，运行`lires server`时，提示`  File "/home/user/.local/lib/python3.11/site-packages/starlette/staticfiles.py", line 59, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'static/' does not exist`，不知道该如何修改

**Comment by MenxLi** [comment]
不是的，你这里主要有两个问题：

1. 从源码安装需要参考Getting Started文档中的[From source](https://github.com/MenxLi/Lires/blob/dev/docs/src/deployment/gettingStarted.md#from-source)进行编译，否则缺少前端文件。
我会定期更新pypi上的包，因此可以直接使用`pip install 'Lires[all]'`安装pypi上的版本，包含了必要文件。

2. `registry`的8700端口是用来服务注册和发现的，`server`才是主要提供服务提供的，默认在8080端口。

**Comment by thormaxx** [comment]
谢谢你的回答！看来是我之前的理解有误。

我重新使用`pip install 'Lires[all]`再次进行了安装。

现在的问题是不知道如何进入使用界面。这几条命令是都要运行吗？
`lires registry  # the global resource module, for service discovery
lires server 
lires log       # the log service
lires ai        # the AI service
lires feed      # the feed service`
比较困惑的是命令行窗口里一次只能运行一条命令，gettingStarted里startup部分没看懂

只运行了`lires server`，根据提示成功通过8080端口访问了登录页面，但是通过下面的register链接没能成功创建用户名和密码。
目前到了这一步，还请方便的时候指教，谢谢

**Comment by MenxLi** [comment]
加用户可以直接使用命令：
`lrs-user add <username> <password>  --admin`

要在网页使用register的话需要用：
`lrs-user invite`
具体可以用`-h`看命令行说明

如果要使用全部功能的话需要运行所有命令的，建议都打开，
只开`server`也可以用，8080端口能访问就行，但是有部分功能会用不了。
